export const actionTypes = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_PRODUCTS_REQUEST: "FETCH_PRODUCTS_REQUEST",
  FETCH_PRODUCTS_FAILURE: "FETCH_PRODUCTS_FAILURE",
  DRAWER_OPEN: "DRAWER_OPEN",
  ADD_TO_CART: "ADD_TO_CART",
};
